// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/styles.css.ts";
import * as $$0 from "./islands/Accordion.tsx";
import * as $$1 from "./islands/GetInTouch.tsx";
import * as $$2 from "./islands/Header/BackgroundHeaderImage.tsx";
import * as $$3 from "./islands/Header/SearchContent.tsx";
import * as $$4 from "./islands/Header/SubMainText.tsx";
import * as $$5 from "./islands/Header/ToggleSearchContent.tsx";
import * as $$6 from "./islands/SliderJS.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/styles.css.ts": $1,
  },
  islands: {
    "./islands/Accordion.tsx": $$0,
    "./islands/GetInTouch.tsx": $$1,
    "./islands/Header/BackgroundHeaderImage.tsx": $$2,
    "./islands/Header/SearchContent.tsx": $$3,
    "./islands/Header/SubMainText.tsx": $$4,
    "./islands/Header/ToggleSearchContent.tsx": $$5,
    "./islands/SliderJS.tsx": $$6,
  },
  baseUrl: import.meta.url,
};

export default manifest;
