// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$0 from "./sections/Accordion.tsx";
import * as $$$$$$1 from "./sections/Comments.tsx";
import * as $$$$$$2 from "./sections/DataSection.tsx";
import * as $$$$$$3 from "./sections/Footer.tsx";
import * as $$$$$$4 from "./sections/GetInTouch.tsx";
import * as $$$$$$5 from "./sections/Header.tsx";
import * as $$$$$$6 from "./sections/Hero.tsx";
import * as $$$$$$7 from "./sections/ParagraphList.tsx";
import * as $$$$$$8 from "./sections/SimpleTextList.tsx";
import * as $$$$$$9 from "./sections/Theme.tsx";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";

const manifest = {
  "sections": {
    "deco-sites/livinrio/sections/Accordion.tsx": $$$$$$0,
    "deco-sites/livinrio/sections/Comments.tsx": $$$$$$1,
    "deco-sites/livinrio/sections/DataSection.tsx": $$$$$$2,
    "deco-sites/livinrio/sections/Footer.tsx": $$$$$$3,
    "deco-sites/livinrio/sections/GetInTouch.tsx": $$$$$$4,
    "deco-sites/livinrio/sections/Header.tsx": $$$$$$5,
    "deco-sites/livinrio/sections/Hero.tsx": $$$$$$6,
    "deco-sites/livinrio/sections/ParagraphList.tsx": $$$$$$7,
    "deco-sites/livinrio/sections/SimpleTextList.tsx": $$$$$$8,
    "deco-sites/livinrio/sections/Theme.tsx": $$$$$$9,
  },
  "apps": {
    "deco-sites/livinrio/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/livinrio/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/livinrio",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
